### PR TITLE
Added UPDs and karyotype

### PR DESCRIPTION
**Pull request by Antonior26**

### CODE REVIEW

**Comment by Antonior26** [comment]
@priesgo docs please.

**Comment by greglever** [comment]
```
INFO:root:Build/s finished succesfully!
Removing intermediate container de64fc3813e5
 ---> d3cc01eaa1f3
Successfully built d3cc01eaa1f3
Successfully tagged gel:latest
root@aa5d201eda2a:/gel# 
```

**Comment by greglever** [comment]
```
----------------------------------------------------------------------
Ran 160 tests in 14.701s

OK
root@aa5d201eda2a:/gel/GelReportModels# 
```

**Comment by Antonior26** [comment]
@greglever, @priesgo can you approve?

**Pull request merged**
