### PR TITLE
Feature - Migrations to reports_4_2_0_SNAPSHOT

### PR DESCRIPTION
**Pull request by greglever**
Summary of Changes
=================
* Add `MigrateReports3To420SNAPSHOT.migrate_interpretation_request_rd` to migrate interpretation requests from version `3.0.0` to `4.2.0-SNAPSHOT`, required by the CIP API.
* Add `TestMigrateReports3To420SNAPSHOT.test_migrate_interpretation_request` to test this

Tests Passing Locally
================
```
(.env) $ python -m unittest discover
............................................
----------------------------------------------------------------------
Ran 44 tests in 2.602s

OK
(.env) $ 
```

### CODE REVIEW

**Comment by priesgo** [comment]
just approved it

**Comment by greglever** [comment]
Please don't merge, I've just realised RDParticipant.chiSquare1KGenomesPhase3Pop for version 3.0.0 is nullable, which causes consternation in the migration scripts...

**Comment by greglever** [comment]
also having trouble with SampleId migration for File objects

**Comment by greglever** [comment]
If you're happy then please merge @priesgo

**Pull request merged**
