### PR TITLE
Release Hotfix 6.0.6

### PR DESCRIPTION
**Pull request by priesgo**
Version 6.0.6 (29th March 2018)
--------------------------------

#### Minor Changes

* Add backwards compatibility to mock data with the hotfix version
* Transaction.avdl including a field to keep track of cva version
* Package participants 1.0.1 is back into the build as it is used by `pythoncommonlibs`

Version 6.0.5 (28th March 2018)
--------------------------------

#### Minor Changes

* Transaction.avdl `TransactionStatus` having a new state `DELETED`
* Transaction.avdl having a record of transaction status changes in `TransactionStatusChange`

Version 6.0.4 (23rd March 2018)
--------------------------------

#### Minor Changes

* Transaction.avdl `TransactionStatus` having two new states `PROCESSING` and `PERSISTING`
* Transaction.avdl `TransactionStatus` has one less state `APPLIED`

Version 6.0.3 (22nd March 2018)
--------------------------------

### Major changes

* Remove hotfix version numbering from build version from 6.0 onwards. To generate any mock data from build 6.0 onwards, the string `6.0` is expected instead of `6.0.0`

#### Minor Changes

* Fixed `MigrateReports400To500().migrate_cancer_interpretation_request` and `MigrateReports400To500().migrate_interpretation_request_rd` that were failing when tested with nullable fields being null. Tests are improved
* Refactored migration tests to use `_validate`

### CODE REVIEW

**Comment by gerlv** [comment]
Also, is there any magic required to run the tests? Just running `./run_tests.sh` fails

**Comment by gerlv** [comment]
@greglever there is an issue, I don't think opencb.py file is generated, @priesgo has this been fixed?

**Comment by greglever** [comment]
@priesgo 
```
INFO:root:Build/s finished succesfully!
Removing intermediate container fa310d56f4b3
 ---> 597133189302
Successfully built 597133189302
Successfully tagged gel:latest
root@a39c81fa9b4b:/gel# cd GelReportModels/
root@a39c81fa9b4b:/gel/GelReportModels# source ./.env/bin/activate
(.env) root@a39c81fa9b4b:/gel/GelReportModels# ./run_tests.sh 
..................................
----------------------------------------------------------------------
Ran 34 tests in 3.922s

OK
(.env) root@a39c81fa9b4b:/gel/GelReportModels# 
```

**Comment by priesgo** [comment]
@gerlv @greglever please check now!

**Pull request merged**
